google_analytics: UA-1241000-10


profiles:
  development:
    disqus: wesleyhales
    disqus_developer: true
  production:
    base_url: http://www.wesleyhales.com/
    disqus: wesleyhales
    deploy:
      host: www.wesleyhales.com
      path: /home/wesley/www.wesleyhales.com
